Update hotswap

diff --git a/hotswap b/hotswap
--- a/hotswap
+++ b/hotswap
@@ -44,12 +44,12 @@ case $arg1 in
 			a=$(($a + 1))
 		done
 
-		read -p 'OpÃ§Ã£o: ' opt
-		[[ $opt =~ ^[0-9]$ && $opt -le $lines ]] || { echo "NÃºmero invalido!"; exit 0 ; }
+		read -p 'Opção: ' opt
+		[[ $opt =~ ^[0-9]$ && $opt -le $lines ]] || { echo "Número invalido!"; exit 0 ; }
 
 		dev=$(echo "$ls" | sed -n "${opt}p" | sed 's/^.*dev\/\(sd[a-z]\).*/\1/')
 		[[ -d /sys/block/$dev ]] || {
-			echo 'Dispositivo nÃ£o conectado!';
+			echo 'Dispositivo não conectado!';
 			exit 1;
 		}
 
@@ -65,12 +65,12 @@ case $arg1 in
 			sleep 1
 
 			udisksctl power-off -b /dev/$dev &> $null && {
-				echo 'Dispositivo pode ser removido com seguranÃ§a!';
+				echo 'Dispositivo pode ser removido com segurança!';
 
 			}||{
 				echo offline > /sys/block/$dev/device/state && \
 				echo 1 > /sys/block/$dev/device/delete && \
-				echo 'Dispositivo pode ser removido com seguranÃ§a!';
+				echo 'Dispositivo pode ser removido com segurança!';
 			}
 			;;
 
