hotswap UP

diff --git a/hotswap b/hotswap
--- a/hotswap
+++ b/hotswap
@@ -1,15 +1,29 @@
 #!/bin/bash
-# Script:		Hotswap
-# Revisao:		0.6
-# Desc:			Conecta e Desconecta dispositivos seriais
-# Autor:		Alan Victor
-# Criado:		04/02/2018
-# Modificado:	21/08/2019
+# Script:			Hotswap
+# Revisao:			0.6
+# Desc:				Conecta e Desconecta dispositivos seriais
+# Autor:			Alan Victor
+# Criado:			04/02/2018
+# Modificado:		21/08/2019
 
+help='
+	USO: hotswap [argumento]
+	EXEMPLO:
 
+		hotswap -s | --scan
+			Levanta dispositivos de armazenamento serial.
+
+		hotswap -d | --delete
+			Desmonta e remove com segurança.
+
+		hotswap -h | --help
+			Mostra Esse help!
+'
 
 clear
+
 echo -en "\n\tHOTSWAP\n"
+
 arg1=$1
 case $arg1 in
 	-s|--scan)
@@ -28,7 +42,6 @@ case $arg1 in
 			echo "Nenhum dispositivo a ser levantado!";
 		}||{
 			echo "Dispositivo levantado: $saida"
-			exit 0;
 		}
 	;;
 
@@ -46,13 +59,13 @@ case $arg1 in
 
 		read -p 'Opção: ' opt
 
-		[[ $opt =~ ^[0-9]$ && $opt -le $lines ]] || { echo "Número invalido!"; exit 0 ; }
+		[[ $opt =~ ^[0-9]$ && $opt -le $lines ]] || { echo "Opção invalida!"; exit 0 ; }
 
 		dev=$(echo "$ls" | sed -n "${opt}p" | sed 's/^.*dev\/\(sd[a-z]\).*/\1/')
 
 		[[ -d /sys/block/$dev ]] || {
 			echo 'Dispositivo não conectado!';
-			exit 1;
+			exit;
 		}
 
 		read -p 'Parece tudo pronto para desconectar, Continuar? [S/n]: ' opt
@@ -69,27 +82,12 @@ case $arg1 in
 
 			*)
 			echo 'Saindo...';
-			exit 0;
+			exit;
 			;;
 		esac
 	;;
 
 	-h|--help|*)
-		clear
-		sc=$(basename $0)
-		echo "
-
-	USO: $sc [argumento]
-	EXEMPLO:
-
-		$sc -s | --scan
-		Levanta dispositivos seriais removidos (hdd, ssd, m2, pendrive, etc).
-
-		$sc -d | --delete
-		Desmonta e remove dispositivos seriais.
-
-		$sc -h | --help
-		Mostra Esse help!
-	"
+		clear ; echo "$help"
 		;;
 esac
