update

diff --git a/hotswap b/hotswap
--- a/hotswap
+++ b/hotswap
@@ -1,41 +1,23 @@
 #!/bin/bash
-# Script: Hotswap
-# Revisao: 0.6
-# Desc: Conecta e Desconecta dispositivos de armazenamento serial
-# Autor: Alan Victor, alanvictorjp gmail com
-# Criado: 04/02/2018
-# Modificado: 28/08/2019
-
-help='
-	USO: hotswap [argumento]
-	EXEMPLO:
-
-		hotswap -s | --scan
-			Levanta dispositivos de armazenamento serial.
-
-		hotswap -d | --delete
-			Desmonta e remove com segurança.
-
-		hotswap -h | --help
-			Mostra Esse help!
-'
+# Script:		Hotswap
+# Revisao:		0.12
+# Desc:			Conecta e Desconecta dispositivos de bloco seriais
+# Autor:		Alan Victor / alanvictorjp gmail com
+# Criado:		04/02/2018
+# Modificado:		19/02/2020
 
 clear
-
 echo -en "\n\tHOTSWAP\n"
-
-null=/dev/null
+null='/dev/null'
 arg1=$1
-
 case $arg1 in
 	-s|--scan)
 		a=$(ls /dev/sd[a-z])
 			for portas in $(ls -d /sys/class/scsi_host/host* | sed 's/^.*host//') ; do
 				echo "- - -" > /sys/class/scsi_host/host$portas/scan
 			done
+
 		b=$(ls /dev/sd[a-z])
-
-
 		for i in $b ; do
 		        saida=$(echo $a | grep -q $i || echo $i)
 		done
@@ -44,13 +26,14 @@ case $arg1 in
 			echo "Nenhum dispositivo a ser levantado!";
 		}||{
 			echo "Dispositivo levantado: $saida";
+			exit 0;
 		}
 	;;
 
 	-d|--delete)
 
 		a=1
-		ls=$(fdisk -l 2> $null | grep '\(^Disco\|^Disk\) \/dev' | sed 's/,\s[0-9]\{4,\}.*//g')
+		ls=$(fdisk -l 2> $null | grep '^Disco\|Disk \/dev' | sed 's/,\s[0-9]\{4,\}.*//g')
 		lines=$(echo "$ls" | wc -l)
 
 		echo "$ls" | \
@@ -60,16 +43,12 @@ case $arg1 in
 		done
 
 		read -p 'Opção: ' opt
+		[[ $opt =~ ^[0-9]$ && $opt -le $lines ]] || { echo "Número invalido!"; exit 0 ; }
 
-		[[ $opt =~ ^[0-9]$ && $opt -le $lines ]] || {
-			echo "Opção invalida!";
-			exit 0;
-		}
-
-#		dev=$(echo "$ls" | sed -n "${opt}p" | sed 's/^.*dev\/\(sd[a-z]\).*/\1/')
-		[[ -d $(echo "$ls" | sed -n "${opt}p" | sed 's/^.*dev\/\(sd[a-z]\).*/\1/') ]] || {
+		dev=$(echo "$ls" | sed -n "${opt}p" | sed 's/^.*dev\/\(sd[a-z]\).*/\1/')
+		[[ -d /sys/block/$dev ]] || {
 			echo 'Dispositivo não conectado!';
-			exit 0;
+			exit 1;
 		}
 
 		read -p 'Parece tudo pronto para desconectar, Continuar? [S/n]: ' opt
@@ -77,21 +56,45 @@ case $arg1 in
 
 		case $opt in
 			s|S)
-			umount /dev/${dev}* 2> $null
-			sleep 2
-			echo offline > /sys/block/$dev/device/state && sleep 1 && \
-			echo 1 > /sys/block/$dev/device/delete && \
-			echo 'Dispositivo pode ser removido com segurança!'
+			cat /etc/mtab | grep 'sdc[0-9]\{1,\}' |sed 's/\s\+.*//' | \
+			while read line ; do
+				umount $line
+			done
+			sleep 1
+
+			udisksctl power-off -b /dev/$dev &> $null && {
+				echo 'Dispositivo pode ser removido com segurança!';
+
+			}||{
+				echo offline > /sys/block/$dev/device/state && \
+				echo 1 > /sys/block/$dev/device/delete && \
+				echo 'Dispositivo pode ser removido com segurança!';
+			}
 			;;
 
 			*)
 			echo 'Saindo...';
-			exit;
+			exit 0;
 			;;
 		esac
 	;;
 
 	-h|--help|*)
-		clear ; echo "$help"
+		clear
+		sc=$(basename $0)
+		echo "
+
+	USO: $sc [argumento]
+	EXEMPLO:
+
+		$sc -s | --scan
+		Levanta dispositivos seriais removidos (hdd, ssd, m2, pendrive, etc).
+
+		$sc -d | --delete
+		Desmonta e remove dispositivos seriais.
+
+		$sc -h | --help
+		Mostra Esse help!
+	"
 		;;
 esac
